### ISSUE TITLE
`includeFilter` does not exist

### ISSUE THREAD

**Issue by mickeyvip** [databrary/sbt-angular-templates#1]
Hello.

Seems like `includeFilter` is not defined as one of `AngularTemplatesKeys`.

Thank you.

**Comment by dylex** [comment]
I believe `includeFilter` is defined in `sbt.Keys`. It's one of the standard `SettingKey`s that many plugins share and should be automatically included in any `build.sbt` for something like:

```
includeFilter in (Assets, angularTemplates) := GlobFilter("*.html")
```

**Comment by mickeyvip** [comment]
Right, my mistake.
