### ISSUE TITLE
Take ownership?

### ISSUE THREAD

**Issue by ghost** [databrary/sbt-angular-templates#4]
@oleastre or @algd  Do you have any interest in taking ownership, maintaining this?

**Comment by oleastre** [comment]
As we are using this in one of our project, I could do that. 
I suppose this would include preparing a sbt 1.0 version (If there is some demand)

**Comment by ghost** [comment]
Awesome! Thanks for responding. We can transfer the ownership from databrary to your preferred org or repo. (cc:  @muji786)

We aren't actively using it, as our main codebase is using Haskell instead of Scala, so it would be good to have an active user own the code.

**Comment by oleastre** [comment]
Transfer of the github repo is now done. Do you have any advice about the publishing on sonatype ? Should I move it to my own namespace ?

**Comment by ghost** [comment]
Probably. I haven't published before. Under your own org/name makes sense.
